services:
  tlfmrw-front:
    container_name: tlfmrw
    build: ./tlfmrw-front
    ports:
      - 3000:3000
    networks:
      - tlfmrw_network

  supabase:
    container_name: supabase
    image: supabase/postgres:17.6.1.052
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 
    environment:
      POSTGRES_PASSWORD: TLFMRW1

    networks:
      - tlfmrw_network
  redis:
    container_name: redis
    image: redis:8.4
    ports:
      - 6379:6379
    networks:
      - tlfmrw_network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  tlfmrw_network: